<a href="https://colab.research.google.com/github/yudhaaamp/Apaajaboleh/blob/main/tugas2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

NumPy (numpy as np) → Digunakan untuk komputasi numerik dan operasi pada array.

Matplotlib (matplotlib.pyplot as plt) → Digunakan untuk membuat grafik dan visualisasi data.

Pandas (pandas as pd) → Digunakan untuk mengelola dan menganalisis data dalam bentuk tabel (DataFrame).

In [51]:
dataset = pd.read_csv('Data_Uni.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

**dataset = pd.read_csv('Data_Uni.csv')**
-> Membaca file CSV bernama Data_Uni.csv ke dalam sebuah DataFrame dataset menggunakan pandas.

**x = dataset.iloc[:, :-1].values**
-> Mengambil semua baris (:) dan semua kolom kecuali kolom terakhir (:-1) sebagai fitur (X).
-> .values mengonversi DataFrame menjadi array NumPy.

**y = dataset.iloc[:, -1].values**
-> Mengambil semua baris (:) tetapi hanya kolom terakhir (-1) sebagai target (Y).

In [52]:
print(x)

[['Vietnam' 27 3.75]
 ['Malaysia' 24 3.77]
 ['Thailand' 26 2.46]
 ['Vietnam' 25 2.17]
 ['Malaysia' 24 3.68]
 ['Singapura' 20 2.08]
 ['Indonesia' 27 2.79]
 ['Singapura' 27 3.22]
 ['Indonesia' 23 3.5]
 ['Malaysia' 26 3.88]
 ['Malaysia' 23 2.82]
 ['Indonesia' 29 3.17]
 ['Thailand' 29 2.8]
 ['Singapura' 27 3.32]
 ['Malaysia' 26 3.74]
 ['Malaysia' 22 3.43]
 ['Thailand' 26 2.61]
 ['Singapura' 22 2.38]
 ['Vietnam' 28 2.05]
 ['Indonesia' 28 2.72]]


In [53]:
print(y)

['Ya' 'Ya' 'Tidak' 'Tidak' 'Ya' 'Tidak' 'Tidak' 'Tidak' 'Ya' 'Ya' 'Tidak'
 'Tidak' 'Tidak' 'Tidak' 'Ya' 'Tidak' 'Tidak' 'Tidak' 'Tidak' 'Tidak']


In [54]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

**from sklearn.model_selection import train_test_split**

-> Mengimpor fungsi train_test_split dari pustaka scikit-learn, yang digunakan untuk membagi dataset menjadi subset pelatihan dan pengujian.

**train_test_split(x, y, test_size=0.2, random_state=0)**

x → Data fitur (input).

y → Data target (output).

**test_size=0.2** → 20% data digunakan untuk pengujian, sedangkan 80% untuk pelatihan.

**random_state=0** → Memastikan pembagian data selalu sama setiap kali kode dijalankan (agar hasilnya konsisten).

**Variabel hasil:**

x_train → Data fitur untuk pelatihan.

x_test → Data fitur untuk pengujian.

y_train → Target untuk pelatihan.

y_test → Target untuk pengujian.

In [55]:
print(x)

[['Vietnam' 27 3.75]
 ['Malaysia' 24 3.77]
 ['Thailand' 26 2.46]
 ['Vietnam' 25 2.17]
 ['Malaysia' 24 3.68]
 ['Singapura' 20 2.08]
 ['Indonesia' 27 2.79]
 ['Singapura' 27 3.22]
 ['Indonesia' 23 3.5]
 ['Malaysia' 26 3.88]
 ['Malaysia' 23 2.82]
 ['Indonesia' 29 3.17]
 ['Thailand' 29 2.8]
 ['Singapura' 27 3.32]
 ['Malaysia' 26 3.74]
 ['Malaysia' 22 3.43]
 ['Thailand' 26 2.61]
 ['Singapura' 22 2.38]
 ['Vietnam' 28 2.05]
 ['Indonesia' 28 2.72]]


In [56]:
print(y)

['Ya' 'Ya' 'Tidak' 'Tidak' 'Ya' 'Tidak' 'Tidak' 'Tidak' 'Ya' 'Ya' 'Tidak'
 'Tidak' 'Tidak' 'Tidak' 'Ya' 'Tidak' 'Tidak' 'Tidak' 'Tidak' 'Tidak']


In [57]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

**SimpleImputer** dari **sklearn.impute** digunakan untuk mengisi nilai yang hilang dalam dataset.

**missing_values=np.nan** → Menentukan bahwa nilai yang hilang di dataset ditandai dengan NaN.

s**trategy='mean'** → Mengisi nilai yang hilang dengan rata-rata dari kolom terkait.

**x[:, 1:3]** → Memilih kolom indeks 1 dan 2 dari x untuk diisi (biasanya kolom numerik).

**.fit()** → Menganalisis data dan menghitung rata-rata untuk kolom yang memiliki nilai NaN.

**.transform()** → Mengganti nilai NaN dengan rata-rata yang telah dihitung sebelumnya.

**x[:, 1:3] = ...** → Menyimpan kembali hasil transformasi ke dalam dataset x.

In [58]:
print(x)

[['Vietnam' 27.0 3.75]
 ['Malaysia' 24.0 3.77]
 ['Thailand' 26.0 2.46]
 ['Vietnam' 25.0 2.17]
 ['Malaysia' 24.0 3.68]
 ['Singapura' 20.0 2.08]
 ['Indonesia' 27.0 2.79]
 ['Singapura' 27.0 3.22]
 ['Indonesia' 23.0 3.5]
 ['Malaysia' 26.0 3.88]
 ['Malaysia' 23.0 2.82]
 ['Indonesia' 29.0 3.17]
 ['Thailand' 29.0 2.8]
 ['Singapura' 27.0 3.32]
 ['Malaysia' 26.0 3.74]
 ['Malaysia' 22.0 3.43]
 ['Thailand' 26.0 2.61]
 ['Singapura' 22.0 2.38]
 ['Vietnam' 28.0 2.05]
 ['Indonesia' 28.0 2.72]]


In [59]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

**ColumnTransformer** digunakan untuk menerapkan transformasi pada kolom tertentu.

**OneHotEncoder()** mengubah data kategori menjadi bentuk biner (0 dan 1).

**fit_transform(x)** menerapkan encoding pada kolom pertama (indeks 0).

**np.array(...)** mengonversi hasilnya menjadi array NumPy untuk kompatibilitas dengan model machine learning.

In [60]:
print(x)

[[0.0 0.0 0.0 0.0 1.0 27.0 3.75]
 [0.0 1.0 0.0 0.0 0.0 24.0 3.77]
 [0.0 0.0 0.0 1.0 0.0 26.0 2.46]
 [0.0 0.0 0.0 0.0 1.0 25.0 2.17]
 [0.0 1.0 0.0 0.0 0.0 24.0 3.68]
 [0.0 0.0 1.0 0.0 0.0 20.0 2.08]
 [1.0 0.0 0.0 0.0 0.0 27.0 2.79]
 [0.0 0.0 1.0 0.0 0.0 27.0 3.22]
 [1.0 0.0 0.0 0.0 0.0 23.0 3.5]
 [0.0 1.0 0.0 0.0 0.0 26.0 3.88]
 [0.0 1.0 0.0 0.0 0.0 23.0 2.82]
 [1.0 0.0 0.0 0.0 0.0 29.0 3.17]
 [0.0 0.0 0.0 1.0 0.0 29.0 2.8]
 [0.0 0.0 1.0 0.0 0.0 27.0 3.32]
 [0.0 1.0 0.0 0.0 0.0 26.0 3.74]
 [0.0 1.0 0.0 0.0 0.0 22.0 3.43]
 [0.0 0.0 0.0 1.0 0.0 26.0 2.61]
 [0.0 0.0 1.0 0.0 0.0 22.0 2.38]
 [0.0 0.0 0.0 0.0 1.0 28.0 2.05]
 [1.0 0.0 0.0 0.0 0.0 28.0 2.72]]


In [61]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

**LabelEncoder()** digunakan untuk mengubah nilai kategori menjadi angka (misalnya, "Ya" → 1, "Tidak" → 0).

**fit_transform(y)** menyesuaikan encoder dengan data dan langsung mengonversinya.

In [62]:
print(y)

[1 1 0 0 1 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0]


In [63]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

 **train_test_split(x, y, test_size=0.2, random_state=1)**

**x** → Data fitur (input).

**y** → Data target (output).

**test_size=0.2** → 20% data untuk pengujian, 80% untuk pelatihan.

**random_state=1** → Memastikan pembagian data tetap sama setiap kali kode dijalankan.

In [64]:
print(x_train)

[[0.0 0.0 0.0 1.0 0.0 26.0 2.46]
 [0.0 1.0 0.0 0.0 0.0 26.0 3.74]
 [0.0 1.0 0.0 0.0 0.0 24.0 3.68]
 [0.0 0.0 1.0 0.0 0.0 22.0 2.38]
 [0.0 0.0 1.0 0.0 0.0 27.0 3.22]
 [0.0 1.0 0.0 0.0 0.0 24.0 3.77]
 [0.0 0.0 1.0 0.0 0.0 27.0 3.32]
 [0.0 0.0 0.0 0.0 1.0 27.0 3.75]
 [1.0 0.0 0.0 0.0 0.0 28.0 2.72]
 [0.0 0.0 0.0 0.0 1.0 28.0 2.05]
 [0.0 1.0 0.0 0.0 0.0 26.0 3.88]
 [0.0 1.0 0.0 0.0 0.0 22.0 3.43]
 [1.0 0.0 0.0 0.0 0.0 23.0 3.5]
 [0.0 0.0 0.0 1.0 0.0 29.0 2.8]
 [1.0 0.0 0.0 0.0 0.0 29.0 3.17]
 [0.0 0.0 1.0 0.0 0.0 20.0 2.08]]


In [65]:
print(x_test)

[[0.0 0.0 0.0 0.0 1.0 25.0 2.17]
 [0.0 0.0 0.0 1.0 0.0 26.0 2.61]
 [1.0 0.0 0.0 0.0 0.0 27.0 2.79]
 [0.0 1.0 0.0 0.0 0.0 23.0 2.82]]


In [66]:
print(y_train)

[0 1 1 0 0 1 0 1 0 0 1 0 1 0 0 0]


In [67]:
print(y_test)

[0 0 0 0]


In [68]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

**StandardScaler()** → Digunakan untuk mengubah skala fitur agar lebih seragam, membantu model machine learning bekerja lebih optimal.

**sc.fit_transform(x_train[:, 3:])** → Menyesuaikan scaler berdasarkan data pelatihan dan mengubahnya ke skala standar.

**sc.transform(x_test[:, 3:])** → Menerapkan transformasi yang sama pada data pengujian tanpa menghitung ulang parameter (mean & std dev tetap dari x_train).

In [69]:
print(x_train)

[[0.0 0.0 0.0 2.6457513110645903 -0.3779644730092272 0.19069251784911848
  -1.0936680867575443]
 [0.0 1.0 0.0 -0.3779644730092272 -0.3779644730092272 0.19069251784911848
  1.0213765229492078]
 [0.0 1.0 0.0 -0.3779644730092272 -0.3779644730092272 -0.5720775535473553
  0.9222338068692038]
 [0.0 0.0 1.0 -0.3779644730092272 -0.3779644730092272 -1.3348476249438292
  -1.2258583748642164]
 [0.0 0.0 1.0 -0.3779644730092272 -0.3779644730092272 0.5720775535473553
  0.16213965025583987]
 [0.0 1.0 0.0 -0.3779644730092272 -0.3779644730092272 -0.5720775535473553
  1.0709478809892095]
 [0.0 0.0 1.0 -0.3779644730092272 -0.3779644730092272 0.5720775535473553
  0.3273775103891793]
 [0.0 0.0 0.0 -0.3779644730092272 2.6457513110645903 0.5720775535473553
  1.0379003089625414]
 [1.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272 0.9534625892455924
  -0.6640496504108601]
 [0.0 0.0 0.0 -0.3779644730092272 2.6457513110645903 0.9534625892455924
  -1.7711433133042385]
 [0.0 1.0 0.0 -0.3779644730092272 -0.377964

In [70]:
print(x_test)

[[0.0 0.0 0.0 -0.3779644730092272 2.6457513110645903 -0.19069251784911848
  -1.5728578811442304]
 [0.0 0.0 0.0 2.6457513110645903 -0.3779644730092272 0.19069251784911848
  -0.8458112965575345]
 [1.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272 0.5720775535473553
  -0.5483831483175223]
 [0.0 1.0 0.0 -0.3779644730092272 -0.3779644730092272 -0.9534625892455924
  -0.49881179027752065]]
